version: '3.9'

services:
  db:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_DATABASE=libace
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: davidccurjc/libace:latest
    ports:
      - "443:8443"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/libace
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=password
    restart: on-failure
volumes:
  db_data:
